#!/bin/bash

SUBJECT=src/cut

assert-equal () {
	# Discard all but the last line to suppress DynamoRIO log
    diff -q <(${RUNNER:-eval} ./$SUBJECT $1 | tail -n 1) <(echo -ne "$2\n") > /dev/null
}

case "$1" in
    1)
        assert-equal "--output-d=: -b1,1234567890- <(echo)" ""
        ;;
esac
